version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: Microsoft.ApplicationInsights.Kubernetes
    versions:
    - 2.0.0
  - dependency-name: Serilog.AspNetCore
    versions:
    - 4.0.0
